# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, '10.0'

target 'LossLess' do
    # Comment the next line if you don't want to use dynamic frameworks
    use_frameworks!
    pod 'YSCheckBox', :git => 'https://github.com/sekies/YSCheckBox.git'
    pod 'DropdownMenu' , :git => 'https://github.com/nmattisson/DropdownMenu.git'
    # Pods for LossLess
end
